# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  piggyhealth-app:
    image: piggyhealth
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://piggyhealth-postgresql:5432/PiggyHealth
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://piggyhealth-postgresql:5432/PiggyHealth
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_ELASTICSEARCH_REST_URIS=http://piggyhealth-elasticsearch:9200
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  piggyhealth-postgresql:
    image: postgres:13.5
    # volumes:
    #   - ~/volumes/jhipster/PiggyHealth/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=PiggyHealth
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
  piggyhealth-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    # volumes:
    #   - ~/volumes/jhipster/PiggyHealth/elasticsearch/:/usr/share/elasticsearch/data/
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'
